### ISSUE TITLE
Links zu pingo.upb.de sind tot

### ISSUE THREAD

**Issue by reitzig** [PingoUPB/pingoupb.github.io#9]
Leider funktionieren sämtliche Sign-Up Links auf trypingo.com nicht.

pingo.uni-paderborn.de scheint zu funktionieren.

**Comment by MichaelWhi** [comment]
Hallo!

Bei uns funktionieren alle Links. 

Welchen Browser nutzen Sie?

**Comment by reitzig** [comment]
![2017-12-01_01](https://user-images.githubusercontent.com/4246780/33484565-1f0d5ebc-d6a3-11e7-8b1b-ddc26a3fe415.png)

**Comment by MichaelWhi** [comment]
nein, ich sitze nicht im Netz der UPB und habe die Auflösung vom normalen DNS-Anschluss, Vodafone LTE und auch mit diversen Tools probiert:
https://dnschecker.org/#A/pingo.upb.de

Dass das bei Ihnen nicht klappt tut mir Leid, evtl. hilft hier aber ein Routerneustart, falls Sie ein privates Netz nutzen; ansonsten kann Ihnen vllt Ihr Rechenzentrum weiterhelfen.
Es nutzen täglich tausende User PINGO erfolgreich von außerhalb, daher haben wir keine Idee woran das nun liefen könnte.

Nichtsdestotrotz habe ich das Netz-Team unseres Paderborner Rechenzentrums mal informiert und gehe davon aus, dass diese die DNS-Konfiguration nochmal genau prüfen werden.

Danke für den Hinweis! Sobald wir da was neues hören, melden wir uns.
Ein schönes Wochenende
